version: "3.4"

services:

  heimdallr-rest:
    image: heimdallr-rest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_CLIENT=mongodb://mongodb:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  heimdallr-migration:
    image: heimdallr-rest
    environment:
      - MONGO_CLIENT=mongodb://mongodb:27017
    depends_on:
      - mongodb
      - heimdallr-rest
    command: [ "poetry", "run", "python", "-m", "heimdallr.migration" ]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db